### ISSUE TITLE
Новый дизайн

### ISSUE THREAD

**Issue by lunavod** [lunavod/ponydays#1]
- [x] Настройки
- [x] Списки
- [x] Выделение комментов
- [x] Кнопки
- [x] Профиль
- [x] Описание блога
- [x] Кнопка "создать"

**Comment by JSkrat** [comment]
http://i.imgur.com/aIk2B8g.png
зачем там такой большой line-height? Некрасиво

**Comment by JSkrat** [comment]
http://i.imgur.com/MQjvWEy.png
алсо чуть ниже цвет
