### ISSUE TITLE
комбинация клавиш "отметить все дочерние комментарии относительно текущего прочитанными"

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#108]
или 10-50 дочерних, проскроллить и оставить текущий каким был, чтобы повтор отмечал следующие 10-50

**Comment by lunavod** [comment]
Так, подробнее.

**Comment by JSkrat** [comment]
стою я значит на комментарии, который развёл срач. И хочу этот срач быстро пролистать, но меня интересует всё остальное в этой ветке, кроме подветки текущего коментария. Вот значит жму клавишу, меня перекидывает на 10-50 каментов вперёд, отмечает их прочитанными, но текущий камент остаётся тем, что и был. Жму ещё раз — следующие 10-50 каментов этой ветки отмечаются так же. И так пока ветка не кончится. 10 мне кажется будет маловато, а 50 уже многовато, тут пробовать нядо
