### ISSUE TITLE
alt+shift+s в чётные разы открывает и закрывает спойлер, в нечётные только открывает

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#117]

**Comment by lunavod** [comment]
Чего?

**Comment by JSkrat** [comment]
полапкай деспойл комента клавиатурой несколько раз. Разные, для точности

**Comment by lunavod** [comment]
https://static.lunavod.ru/img/dad72b267da4bfe6cbaf3e183bd82a29a32bc65c.gif

**Comment by JSkrat** [comment]
или ты починил, или я неправильный путь воспроизведения указал, у меня сейчас тоже не дёргается, хотя страницу не перезагружал. Не закрывай пока

**Comment by JSkrat** [comment]
окей, оно срабатывает дважды, но не всегда. Вот сейчас на новом комментарии через c+space сделанном открыл alt+shift+s и оно первый раз блинкнуло, а второй раз и дальше перестало

**Comment by JSkrat** [comment]
Вот так всё и происходит, управляю исключительно клавиатурой
![lunavod](https://cloud.githubusercontent.com/assets/15997389/25012604/a7d0cfee-2079-11e7-9fc1-fc7c252c2a6b.gif)
не зависит от количества спойлеров
