### ISSUE TITLE
В заголовке окна показывается неправильное количество непрочитанных комментов

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#118]
1-2. А внутри может быть 7 или 9.

**Comment by JSkrat** [comment]
о, ты уже создал)
http://i.imgur.com/cpgAQwx.png
http://i.imgur.com/sDmmpKE.png

**Comment by Ori-Lama** [comment]
![](http://i.imgur.com/cpgAQwx.png)
![](http://i.imgur.com/sDmmpKE.png)
(а мне не лень код картинки написать)

**Comment by Ori-Lama** [comment]
Теперь правильное, но во время прощелкивания оно не уменьшается. Когда все прощелкаешь - исчезает.

**Comment by lunavod** [comment]
Но... Я ведь... Ничего не менял...
