### ISSUE TITLE
не видно, что картинка аплоадится по ссылке

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#119]
и теперь это стало как-то очень долго

**Comment by lunavod** [comment]
Потому что анонимайзер.

**Comment by JSkrat** [comment]
и не выдаются сообщения об ошибке, хотя сервер пишет вполне вразумительный текст

**Comment by JSkrat** [comment]
как фикс? лоадера как не было, так и нет...
кнопки-то хоть не залипают теперь при ошибке, но лоадер-то!

**Comment by lunavod** [comment]
Так а какого лоадера? Где про него была речь? О_о

**Comment by JSkrat** [comment]
"не видно"
единственный признак, что что-то происходит - кнопка самую малость меняет цвет, становясь неактивной на момент загрузки.
