### ISSUE TITLE
Наиболее глубоко вложенную ветку надо сделать шире

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#125]
![](http://i.imgur.com/RZLBNfo.png)
Все-таки это &uarr; не круто )

**Comment by lunavod** [comment]
Так, стоп. Ты просишь сделать минимальную ширину коммента шире? Или наоборот?

**Comment by Ori-Lama** [comment]
Ну да, чтобы такие ветки были шире, а то ж читать невозможно.

**Comment by lunavod** [comment]
А на сколько? Вот сейчас минимальная ширина коммента - 250. Сколько сделать?

**Comment by Ori-Lama** [comment]
![](http://s01.geekpic.net/di-GBDQEP.png)
Так, ну вон там была примерно пятая часть экрана по ширине и в принципе читаемо. Можно сделать четверть экрана по ширине. Или относительные размеры задавать нельзя?

**Comment by lunavod** [comment]
D:
Как-то многовато, как по мне. Хотя мне и так как сейчас нормально, да. Надо бы настраиваемым это сделать. И относительные можно, но не нужно. Например, четверть экрана телефона - это мало.

**Comment by Ori-Lama** [comment]
Ну сделай хотя-бы как на бункере было.

**Comment by lunavod** [comment]
В смысле? Я ж про скрин и говорю. Как по мне, там слишком широкие комменты, можно сильно уже. Тут кстати настраиваемым это сделать вполне просто. Так что каждый сможет сам задать.

**Comment by Ori-Lama** [comment]
А самый первый скрин ты не видел? Это же ужасно, когда тексты растягиваются вот в такие колонки.

Настраиваемость - это хорошо, потому что как видно, вкусы у всех сильно разные в этом вопросе.

**Comment by lunavod** [comment]
Да нет, видел. И сам читал ту ветку. И мне вполне норм было. Я ж не от балды 250 туда поставил. :D

**Comment by Ori-Lama** [comment]
Ну а я такое видеть не могу просто )
