### ISSUE TITLE
Починить деспойл

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#129]
Бывает, что Ози пишет текст в spoiler-body без spoiler-head, да и не только он, раньше писали - а теперь Песец те комменты иногда находит и от этого деспойл по всей странице ломается. Заставить его не писать такое и не искать Песцом я не смог )

**Comment by lunavod** [comment]
Так починил ж уже.

**Comment by Ori-Lama** [comment]
Нет, в текущей флудилке он не работает. Где-то видимо Ози успел оставить фигню.

**Comment by lunavod** [comment]
У меня работает, только что проверил. О_о

**Comment by Ori-Lama** [comment]
Сейчас проверил. Открывается, но обратно не закрывается.

**Comment by Ori-Lama** [comment]
Проверил в файрфоксе - то же самое. Так что дело не в моем странном браузере.

**Comment by lunavod** [comment]
Не закрывается да. Но он же деспойл... D:

**Comment by Ori-Lama** [comment]
На кнопке написано spoil/despoil и раньше он так работал. Окей, сделаю ишшую с названием "Создать деспойл"...
