### ISSUE TITLE
Перенести уведомление о редактировании в информацию о комментарии

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#133]
Ну, это скорее предложение чем баг.
![](http://s01.geekpic.net/di-TPPAH1.png)
Cдвинуть бы туда эту надпись, чтобы высота отредактированного коммента оставалась прежней. А то они слишком в глаза бросаются.

**Comment by lunavod** [comment]
Надо придумать, куда это можно впихнуть на бункере. Потому что сейчас при редактировании эта штука добавляется в тело коммента.
