### ISSUE TITLE
Голосовые комментарии

### ISSUE THREAD

**Issue by lunavod** [lunavod/ponydays#136]

**Comment by ghost** [comment]
О, меня назначили. Ладно.

**Comment by JSkrat** [comment]
tts? =D

**Comment by lunavod** [comment]
Не. Запись голоса, как в ВК.

**Comment by MineOzelot** [comment]
Никто не любит запись голоса. Особенно как в ВК.

**Comment by lunavod** [comment]
Да, возможно нафиг эту штуку  >_>

**Comment by lunavod** [comment]
Я не помню, но там вроде ситуативно оно тогда было нужно Х)

**Comment by Frumscepend** [comment]
Тут можно было бы просто вставлять любой звук, запись с микрофона - это просто опция.
