### ISSUE TITLE
Заголовок флудилки иногда становится "unknown"

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#151]
Не оттого ли что ее закрыли?

**Comment by lunavod** [comment]
Не должно быть связано.

**Comment by MineOzelot** [comment]
Как давно он это делал?

**Comment by Ori-Lama** [comment]
Ну, когда ишшую создали, тогда и делал ) Потом это починили вроде, сейчас нет такого.

**Comment by MineOzelot** [comment]
Ну так закрывать надо
