### ISSUE TITLE
Добавить target="_blank" к этим ссылкам в шапке

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#154]
![](http://s01.geekpic.net/di-DEU69K.png)

**Comment by lunavod** [comment]
Хм. На самом деле, таки весьма сомнительная идея...

**Comment by Ori-Lama** [comment]
Промазал по кнопке - непрочитанные комменты во флудилке потерял.
Сделать тогда что-то для сохранения текущей непрочитанности, чтобы она не терялась при переходе по ссылкам.

**Comment by lunavod** [comment]
В новом дизайне не нужно, ибо не промажешь.
