### ISSUE TITLE
Сделать wide mode

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#159]

**Comment by Ori-Lama** [comment]
При переходе в вайд-мод комменты желтеют и кнопки не нажимаются.
Хм. Сделал второй раз - кнопки нажимаются, но комменты все равно желтеют.

**Comment by lunavod** [comment]
Но я ж фиксил... D:

**Comment by lunavod** [comment]
Да, проверил, все норм

**Comment by Ori-Lama** [comment]
О, в wide-mode не работают горячие клавиши.

**Comment by Ori-Lama** [comment]
И при переключении обратно не работают. Обновил страничку - работают.

**Comment by Ori-Lama** [comment]
При нажатии на кнопку вайдмода перезагружается страница и кнопки "Ответить" не работают. А еще все становилось желтым, будто непрочитано.
