### ISSUE TITLE
Подвисание страницы на пару секунд при переключении с другой вкладки

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#160]
При переключении с вкладки с плеером ютюба флудилка с 600+ комментами подвисает на пару секунд. Потом отвисает и норм. Я понимаю, конечно, что ютюб тяжелый, но кажется раньше подобного не наблюдалось. Фиг знает, это у меня так браузер стал странно работать или тут что-то сломалось.

**Comment by lunavod** [comment]
Не воспроизводится.

**Comment by Ori-Lama** [comment]
Ты тогда говорил что починил что-то из-за чего все висло. С тех пор норм.
