### ISSUE TITLE
На кнопку обновления комментариев повесить "мягкое" обновление

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#166]
Либо развести кнопку и и циферки подальше, на такое же расстояние как и другие кнопки.
![](http://i.imgur.com/XLNvqlB.png)

**Comment by Max-Maximilian-Maxwell** [comment]
Хм...

**Comment by lunavod** [comment]
Это работает странно. При обновлении комментов, если новых нет, ощущение что что-то не работает. Я даже на автомате полез в консоль, смотреть где ошибки. XD

**Comment by MineOzelot** [comment]
А как их потом сбрасывать?

**Comment by Ori-Lama** [comment]
А, дошло. Непрочитанность сбрасывается прощелкиванием кнопки с числом непрочитанных или обновлением страницы, как и сейчас.

**Comment by MineOzelot** [comment]
Щелкать 600 раз не очень, и после какого-нибудь супер изменения, сохраняющего комменты после перезагрузки, это будет невозможно.

**Comment by Ori-Lama** [comment]
Я обычно щелкаю до тех пор, пока не начнется новая корневая ветка, а потом сбрасываю нажатием на кнопку обновления комментов. Если сильно много, то щелкаю через Ctrl+Space.

Если такое супер-изменение будет, я буду только рад, потому что неоднократно терялась непрочитанность и приходилось скриптом в консоли восстанавливать, а сейчас этот скрипт только на старом бункере работает..

Главное - избежать случайного сброса непрочитанности. Развести кнопку сброса и циферки подальше. Или сделать кнопку отмены сброса. Или повесить на кнопку обновления мягкое обновление, а где-нибудь в другом месте сделать кнопку жесткого обновления.. Много вариантов.

**Comment by MineOzelot** [comment]
Мне только последний кажется стоящим.. Но вгде?

**Comment by Ori-Lama** [comment]
Надо спросить у людей, которые этой кнопкой пользуются. Мне она практически не нужна, потому что автообновление идет всегда. Поэтому я бы ее вообще убрал. Можно сделать всплывающую менюшку с дополнительными функциями, вот как сейчас всплывает справка по клавиатуре в углу. Можно туда в эту справку и засунуть..

**Comment by MineOzelot** [comment]
Мобильные устройства бы учитывать.

**Comment by Ori-Lama** [comment]
![](https://i.imgur.com/dZwRsue.png)

**Comment by MineOzelot** [comment]
Тулбар разлепляют!

**Comment by Ori-Lama** [comment]
Я не дизайнер и свое мнение об этой кнопке сказал. Она не нужна, потому что есть автообновление. Кнопка прощелкивания непрочитанных нужна. На реакторе, например, это горячая клавиша без модификаторов, просто k. (Хотя логичнее j как в vim :) Кнопка сброса непрочитанности? Ну можно и сделать..

**Comment by MineOzelot** [comment]
Заставляют меня думать >->
Я вообще хотел с шифтом её кликать, чтобы сбрасывать. Но на мобильных устройствах нету шифта.

**Comment by Ori-Lama** [comment]
Проще всего тогда сделать вторую кнопку и положить ее над деспойлом, например. Деспойлом редко пользуются значит случайных нажатий будет меньше.

**Comment by MineOzelot** [comment]
Кажется, это нарушает.. Функциональное соседство кнопок?
И какую [картинку](http://fontawesome.io/icons/) на нее налеплять?

**Comment by Ori-Lama** [comment]
Функциональное соседство кнопок обеспечивает промахивание пользователем по сходной функции ) А так при промахе ничего страшного не случится. Картинку такую же, просто фон красный, например.

**Comment by MineOzelot** [comment]
Не думаю, что менять цвет - хорошая идея..

**Comment by Ori-Lama** [comment]
Тогда сделай ее восьмиугольной как знак STOP, лол :D

**Comment by MineOzelot** [comment]
Как же сложно решить, как должна выглядеть кнопка! D:

**Comment by ghost** [comment]
Всю почту засрали, бл*ть.

**Comment by MineOzelot** [comment]
Сам подписался >->

**Comment by lunavod** [comment]
Вот так!
![hydrr_croper_ru](https://user-images.githubusercontent.com/14801311/33010325-2ae454fe-cdeb-11e7-9f4f-b23c0c4d659e.png)
И ничего никуда сползать не будет. При отсутствии новых кнопка не исчезает а просто деактивируется.
![image](https://user-images.githubusercontent.com/14801311/33010362-47ebf46c-cdeb-11e7-97d4-cd8d5d0a58e7.png)
Да и ниже нее кнопок нет.

**Comment by MineOzelot** [comment]
А сбрасывать то как?

**Comment by lunavod** [comment]
Нажатием на кнопку обновления. Мягкий апдейт вешать просто не надо. Ибо так он нинужин на кнопке.

**Comment by MineOzelot** [comment]
Это же против цели issue .-.

**Comment by lunavod** [comment]
Они в описании писал же, что можно просто разнести. Его цель была убрать проблемное поведение. Тут его не будет.

**Comment by MineOzelot** [comment]
Цель была - убрать попадание по сбросу, вместо перехода на следующий новый

**Comment by lunavod** [comment]
Ну так. Тут такой проблемы нет. Обе кнопки большие, попасть по другой надо постараться.

**Comment by MineOzelot** [comment]
Чем сложнее, чем сейчас?

**Comment by lunavod** [comment]
Обе кнопки больше. Кликают обычно ближе к центру. В тулбаре кнопки маленькие, центры ближе, промазать проще.

**Comment by JSkrat** [comment]
так шо, будет мягкое обновление заместо жёсткого по циферке?

**Comment by MineOzelot** [comment]
Давайте определим, существует проблема сейчас или нет.

**Comment by Ori-Lama** [comment]
Похоже, проблема была устранена с новым дизайном. Не помню чтобы попадал на кнопку обновления, когда целился по "следующий непрочитанный". Да и горячая клавиша "s" сделала совсем все хорошо.
