### ISSUE TITLE
Не работает удаление поста

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#168]
Жмешь "Удалить" - ничего не происходит. Пост не прикреплен к блогу.

**Comment by lunavod** [comment]
Это по идее закрыто корзиной?

**Comment by Ori-Lama** [comment]
Ну, если она нормально работает, то да.. У меня как-то руки не дошли протестить корзину, не пригодилась еще.

**Comment by Frumscepend** [comment]
Да, работает нормально.
