### ISSUE TITLE
Улучшить получение ссылки на цитату в цитатнике

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#181]
Почему ссылку на цитату надо получать щелчком и копировать из окошка? Лучше сделать как с комментами, пусть этот октоторп и будет ссылкой, которую можно сразу скопировать.

Либо, если такое возможно, то просто щелчок по октоторпу чтоб клал ссылку в буфер обмена.

**Comment by Silvman** [comment]
Это хэш >_>
В целом, это даже легче сделать... Правда это будет совсем нет так как с комментами. Комменты дают ссылку вида /blog/fir/123#comment_id, а тут будет просто /quotes/401, технически это ссылка не на саму цитату, а запрос, который ищет страницу, где находится цитата с id 401 и переадрессовывает уже на страничку с цитатой.

**Comment by Ori-Lama** [comment]
Ну вот. А то сейчас ссылка достается в два щелчка и Ctrl+C, а так будет один правый щелчок и один левый.

**Comment by lunavod** [comment]
Теперь хэштег - ссылка.
