### ISSUE TITLE
Чтобы всё содержимое удалённых комментов автоматически заносилось под обычный спойлер

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#182]
Заходишь в старый пост с удаленной порнухой - видишь порнуху.
https://alpha.lunavod.ru/blog/flud/3037#comment1179041

**Comment by Ori-Lama** [comment]
Проблема вернулась. Удаленный комментарий, написано "Раскрыть комментарий", но он уже раскрыт. При нажатии на надпись надпись исчезает. Перед началом чтения флудилки жал деспойл, может из-за этого?
![](https://i.imgur.com/EVwVrmu.png)

**Comment by MineOzelot** [comment]
Есть так. Это же обычный спойлер >->

**Comment by Ori-Lama** [comment]
Ну, надо чтобы они не раскрывались при деспойле, потому что какой смысл в них тогда?

**Comment by MineOzelot** [comment]
Ну..
> Видимо тогда я думал о том, чтобы это содержимое можно было легко массово деспойлить и спойлить обратно, в случае необходимости.

Тогда нужно еще подумать о непрогрузке картинок в закрытых штуковинах.

**Comment by Ori-Lama** [comment]
Ну не надо значит их массово деспойлить.

**Comment by MineOzelot** [comment]
Может текст этих комментов не получать сначала, а запрашивать у сервера по клику?

**Comment by Ori-Lama** [comment]
Может? Я не знаю как это может или не может работать, я не вебщик.

**Comment by MineOzelot** [comment]
Я тоже >->

**Comment by MineOzelot** [comment]
Потыкай эту штуковину

**Comment by Ori-Lama** [comment]
Работает, деспойл не деспойлит, кликом открывается.

**Comment by MineOzelot** [comment]
Все хорошо? Тогда закрой.

**Comment by Ori-Lama** [comment]
А почему я?

**Comment by MineOzelot** [comment]
Чтобы не писать еще коммент >->

**Comment by Ori-Lama** [comment]
Слушай, я не разбираюсь в этих ваших гит-штучках, мне про закрытие никто ничего не объяснял, когда сюда звали. Мне сказали "пиши баги вот сюда" и я просто пишу. Закрывали вы тут всегда все сами когда вам это было нужно. Я не лезу туда, где могу что-то сломать.

**Comment by MineOzelot** [comment]
Рядом с "Comment" кнопка для закрытия/открытия же есть..

**Comment by Ori-Lama** [comment]
Дело не в том, что кнопка есть, а в том, что не в моей компетенции ее нажимать.

**Comment by MineOzelot** [comment]
Можешь создавать - можешь закрывать, почему нет?

**Comment by Ori-Lama** [comment]
Потому что мне не сказали об этом. Потому что разработчик может быть еще что-то хочет дописать потом и поэтому не закрывает, чтобы не забыть потом. Такие вещи должен разработчик решать.

**Comment by MineOzelot** [comment]
Кто этот разработчик?

**Comment by Ori-Lama** [comment]
Лунавод, Сильвман, а теперь и ты, видимо.

**Comment by MineOzelot** [comment]
Тогда не вижу проблемы тут.
