### ISSUE TITLE
Добавить на главную ссылку в текущую флудилку

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#184]
А-ля...
![](http://s01.geekpic.net/di-XQCO5U.png)

Ссылка ведет на самый новый пост в блоге "Флудилка!", например. Да, иногда в блоге появлялись всякие голосования и прочее подобное, но очень редко и сейчас такого нет. Так что такой простой алгоритм мог бы и сработать )

**Comment by MineOzelot** [comment]
Завершено в 21b1008b5c1532df43b69b3af09047d3853ddef6
