### ISSUE TITLE
Деспойл в файрфокс

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#195]
В хроме если нажимать на спойл/деспойл, то положение на экране не меняется. Спойлеры по всей странице открываются и закрываются, но ничего никуда не съезжает. А в файрфоксе съезжает: спойлеры открываются, страница становится больше, а ты как бы остаешься стоять на месте и все уезжает вниз. Это можно исправить средствами сайта или это неисправимо, потому что браузеры так работают?

**Comment by lunavod** [comment]
Судя по всему таки это браузеры так работают.
