### ISSUE TITLE
Иконки иногда пропадают при открытии страницы

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#21]
Вот эти вот.
![иконки](http://s01.geekpic.net/di-X44SMB.png)
И еще в редакторе комментария тоже пропадают. И справа кнопки перемотки вниз-вверх.
Выход-вход из аккаунта помогает.

**Comment by lunavod** [comment]
Вход-выход из аккаунта помогает из-за того, что альфа на http. Окей, надо таки принудительно перетащить и бункер, и альфу на https, и пофиксить все связанное с этим...
