### ISSUE TITLE
Закрасить кнопку голосования за пост после голосования

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#215]
![](https://i.imgur.com/PBphTxS.png)
Не видно голосовал я за пост или нет, надо чтобы подсвечивалось. Например, закрасить всю кнопку зеленым, а стрелку сделать белой.

**Comment by lunavod** [comment]
Это нужны стили .vote-up.voted и .vote-down.voted.

**Comment by Farxial** [comment]
Какие это должны быть стили, чтобы было красиво?
- Я подумал, что можно было бы слегка менять фон кружочка в сторону зелёного/красного, но получается слишком цветасто для текущего стиля.
- Можно немного увеличить размер шрифта и/или добавить `font-weight: bolder;`, но так наоборот почти незаметно.
   - Ещё можно добавить `text-shadow`, но это помогает не сильно, а `text-shadow` с blur-radius=1px уже выбивается из текущего стиля.
> Например, закрасить всю кнопку зеленым, а стрелку сделать белой.

Не будет ли это слишком цветасто для текущего стиля?

**Comment by Ori-Lama** [comment]
Хм, и правда ярковато. Я попробовал #CAFFCD на background vote-up voted. Чет такое можно.

**Comment by lunavod** [comment]
![](https://i.imgur.com/xB0EcUo.png)
![](https://i.imgur.com/b2OyXRO.png)
Предлагаю такие варианты

**Comment by Ori-Lama** [comment]
Второй лучше, первый почти не видно.

**Comment by Farxial** [comment]
Цвет во 2-м варианте — для обеих цветовых тем? (Сорри за дурацкий вопрос.)

**Comment by lunavod** [comment]
Ага, для обеих. Просто $brand.

**Comment by Farxial** [comment]
OK.

Но... По-хорошему, при голосовании надо сразу поменять стили кнопок, но там по-разному расположены классы для топиков и комментов:
- У комментов `.vote-up|.vote-down|.vote-count` внутри `[.voted-up]&[.voted-down]&[.voted]`
- У топиков `.vote-up|.vote-down &[.voted]` внутри `.vote-count`
(Также у родительских элементов может быть `.vote-count-(positive|negative|mixed)` (mixed добавил я).) И с этим надо что-то делать: либо сделать у топиков примерно как у комментов, либо в скрипте искать кнопку, которой, в случае переголосования, надо убрать `.voted`. И какой вариант лучше выбрать? ![ae60e4](https://user-images.githubusercontent.com/19311376/34906448-1de5aed8-f87f-11e7-919b-39209a5ef713.png)
Или можно только добавить стиль, но кнопки обновятся только после обновления страницы и это так себе вариант.
----------
OK, попробую вариант 1.
