### ISSUE TITLE
Сохранение пропущенных уведомлений

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#219]
Отвлекся, отвернулся, отошел, был на другой вкладке, был в другом окне - в общем, так или иначе проглядел всплывашку. Она появилась на три секунды, а потом исчезла навеки. Ты слышал чпок, но не успел. Должна быть возможность достать упущенное. Некая область уведомлений, в которой сохраняются непрочитанные уведомления или типа того.

**Comment by lunavod** [comment]
В идеале модифицировать модуль ответов для этого. При показе проверять дату просмотра топика, и отмечать те что уже просмотрены. Можно подгружать по ajax при открытии, можно сразу добавлять уведомления когда приходят сообщения от вебсокетов.

**Comment by Frumscepend** [comment]
Сделано.
