### ISSUE TITLE
Баг при логине

### ISSUE THREAD

**Issue by Frumscepend** [lunavod/ponydays#220]
Если снять галочку «Запомнить меня» во время логина, то в дальнейшем постоянно всплывает сообщение об ошибке и не работают звуковые оповещения.

**Comment by lunavod** [comment]
Чинится записью куки ws_key не только при логине с запоминанием. Но тогда надо писать ее без даты истекания, чтобы удалялась при закрытии браузера. А то будут идти уведомления незалогиненным.
Это все в ModuleUser.
