### ISSUE TITLE
Скрывать комментарии, приходящие в свернутую ветку

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#224]
М, похоже что не всегда новые комменты появляются поверх свернутой ветки. Предполагаю, что только те, которые являются ответом на коммент, под которым ветка свернута. Надо тогда заблокировать прощелкивание скрытых комментов через кнопку перехода к следующему непрочитанному комментарию. То есть сделать их заочно прочитанными.

**Comment by lunavod** [comment]
Нет, заочно прочитанными делать не надо. Чтобы при развороте ветки комменты становились новыми. Надо сделать чтобы комменты шли в свернутость, и проверить где не хватает флага :visible в селектора .comment-new
