### ISSUE TITLE
Если администратор/модератор сохраняет текст коммента пользователя, не изменив его, пользователю всё равно приходит уведомление, а коммент получает статус изменённого

### ISSUE THREAD

**Issue by Farxial** [lunavod/ponydays#229]

**Comment by lunavod** [comment]
Это вроде фиксили же? Во всяком случае сейчас если не изменить коммент, то оно его и не изменяет, говорит что иди нафыр, текст такой же.

**Comment by Frumscepend** [comment]
Да, все было исправлено...

**Comment by lunavod** [comment]
Ну, тогда можно закрывать же.
