### ISSUE TITLE
Ошибки во время бесконечного скролла ленты

### ISSUE THREAD

**Issue by Frumscepend** [lunavod/ponydays#232]
При нажатии на `Получить ещё топики ↓`  вместе с новыми иногда дублируются старые.

**Comment by Frumscepend** [comment]
Дублируется топик №6 сверху.

**Comment by MineOzelot** [comment]
Напомните мне, "лента" - это куда?

**Comment by Ori-Lama** [comment]
Это на главной. Вниз мотаешь, там такая кнопочка:
![](https://i.imgur.com/cO0BHMN.png)
Сейчас потыкал, дублей не наблюдаю. Но раньше действительно появлялись.

**Comment by MineOzelot** [comment]
Я тоже помню, что появлялись. Но сейчас что с этим делать.. И что именно это пофиксило..

**Comment by Frumscepend** [comment]
Если само пофиксилось, то надо закрывать.

**Comment by MineOzelot** [comment]
Сказал он, и сам не закрыл.
