### ISSUE TITLE
Галочка запрета смены ранка администраторами по их прихоти

### ISSUE THREAD

**Issue by lunavod** [lunavod/ponydays#259]
Если включена, отображать над полем смены ранка в инфе для админов предупреждение, что пользователь запретил менять ему ранк. Саму возможность лучше оставить, но за нарушение карать. Т.е. если например пользователь попросил заменить на определенный, потому что сам не может (по какой-то причине, не суть важно) - окей, не вопрос. Или если там что-то, нарушающее правила. Но если просто по прихоти левой пятки админа - карать.

**Comment by Frumscepend** [comment]
Может тогда это отдать модерам?

**Comment by lunavod** [comment]
Можно, да.

**Comment by Farxial** [comment]
Согласно #258, ранк должен определять пользователь, пусть даже после валидации. Если так, то почему админы должны иметь возможность менять его по своей воле? +Дополнительное неудобство: сначала пользователь пытается поменять свой ранк и сталкивается с ограничением, а потом, после его установки, кто-то легко меняет его на другой. При таком сценарии включение опции более рационально со стороны пользователя, чем отключение, а если такой сценарий вообще допустим, то со стороны админов/кодеров будет справедливо сразу и нейтрализовать его, включив эту опцию по умолчанию. А если опция включена по умолчанию, зачем пользователь может захотеть её отключить, если сам может менять свой ранк? Ситуация, в которой он не сможет сделать это сам, может быть в будущем и он может о ней на тот момент не знать.
> потому что сам не может (по какой-то причине, не суть важно)

Но это вообще возможно? ЛС админу он написать может, а сменить ранк — нет. А если он пишет не через Бункер, то имеет место ситуация, когда он просто не имеет доступа к Бункеру. Но зачем ему тогда вообще ранк, пока он не получит доступ к Бункеру?
> Или если там что-то, нарушающее правила.

Можно удалить ранк, удаление безопаснее изменения.

**Comment by Frumscepend** [comment]
@Farxial Я так понял "валидация" - это санитайз.

**Comment by lunavod** [comment]
Не нужно.
