### ISSUE TITLE
Невозможно вернуться назад из картинки, по которой щелкнул

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#26]
[пример картинки](https://alpha.lunavod.ru/blog/flud/2654#comment949382)

Посмотри как клево сделано управление открытой картинкой [на Пикабу](http://pikabu.ru/story/chto_tam_u_nas_pingvinyi_4903181), хорошо было бы и здесь так сделать, раз уж эта функция появилась в голове )

**Comment by Ori-Lama** [comment]
А это таки было пофикшено или просто отложено? Другие фиксы я увидел, а этот вроде не сработал еще.

**Comment by lunavod** [comment]
Я таки пофиксил. Правда, не сделал так как на пикабу - там много работы, нечто подобное я сделаю уже потом. Однако баг закрыт - я ограничил максимальную высоту и ширину открываемой картинки до 98%, так что место будет всегда. Хотя, сейчас мне кажется, что стоит еще сделать закрытие по клику на саму картинку...

А, и таки, думаю, такое я сделаю, когда буду добавлять #9 - ибо там таки планируются теги и всякое такое, так что в любом случае этот блок придется переделывать.

**Comment by Ori-Lama** [comment]
Странно, что закрытие картинки по щелчку на нее тебе не пришло в голову сразу же ) Я думал, именно это и нужно сделать. Потому что лезть куда-то в край чтобы закрыть картинку - это странно.

**Comment by lunavod** [comment]
`$("#image-modal-img").click(function(){$("#image-modal").css("display", "none")})`
Стоп, а это уже есть. Тогда какого черта оно не работает? О_о

**Comment by Ori-Lama** [comment]
Сейчас Ctrl+F5-нул на главной, проверил, работает.

**Comment by lunavod** [comment]
Ага, ибо я починил. :D
