### ISSUE TITLE
Style: Подсветка кода в превью

### ISSUE THREAD

**Issue by Frumscepend** [lunavod/ponydays#276]
Не работает подсветка синтаксиса в всплывающем превью

**Comment by lunavod** [comment]
А марк тут при чем?

**Comment by Frumscepend** [comment]
Ну, так он же не подсвечивается)

**Comment by lunavod** [comment]
В смысле? Разве ты не про подсветку в коде? Она с марком вообще не связана.

**Comment by Frumscepend** [comment]
А, ну ок. Значит стайл.

**Comment by lunavod** [comment]
Она работает даже в обычном коде. Это просто отдельная библиотека для подсветки, которая ищет на странице или в нужных элементах `pre code` и делает их круче. Х)
