### ISSUE TITLE
Поле ввода пользовательских тегов для избранного слишком большое

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#278]
Этим пользуются настолько редко, что я заметил только сейчас ) Тем не менее, поле ввода этих тегов надо сделать поменьше.
![](https://i.imgur.com/dq7Fi4u.png)

**Comment by Frumscepend** [comment]
Видимо это я сломал(

**Comment by Frumscepend** [comment]
@MineOzelot Не воспроизводится сейчас?

**Comment by Ori-Lama** [comment]
Ози починил.

**Comment by Frumscepend** [comment]
@Ori-Lama Ну не коммитом закрыто, по этому не понятно.
