### ISSUE TITLE
Не могу залогиниться

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#28]
Зашел на https://alpha.lunavod.ru/ - нажимаю кнопку входа, появляется формочка, хром подставляет логин-пароль. Нажимаю кнопку - ничего не происходит, не входит. Пароль перепроверил - вставляется правильный.

**Comment by Ori-Lama** [comment]
Прожал ctrl+F5 пару раз - не помогает.

**Comment by Ori-Lama** [comment]
Зашел внутрь флудилки, оказался уже не на https, а на http. Залогинилось. Я пробовал до этого зайти на главной через http - все равно не получалось. А из поста получилось.

**Comment by Ori-Lama** [comment]
Вот, и после произведенного таким макаром входа я жму на главной f5 - и там иконки отваливаются.

**Comment by Ori-Lama** [comment]
Выхожу-вхожу - иконки снова на месте.

**Comment by lunavod** [comment]
Иконки отваливаются на https. Альфа работает через http. Попробовал воспроизвести. На главной через http залогинило с первого раза... Можешь кинуть, что в network, в запросе к ajax-login (сначала открой нетворк, потом нажимай на кнопку входа)?

**Comment by Ori-Lama** [comment]
![](http://s01.geekpic.net/di-4PG9MW.png)
это вот если по https заходить пытаться

**Comment by Ori-Lama** [comment]
Через http вошел с первого раза тоже.

**Comment by lunavod** [comment]
Не. Меня интересует, почему не получается зайти через http, ибо с https-то все ясно...

**Comment by lunavod** [comment]
Хм, ясно. Видимо, опять какая-то фигня с обновлением паролей, которую я не могу отловить. Пегасик, пфырный он такой. Кинул мне неоттестированный патч, и не предупредил об этом.

**Comment by lunavod** [comment]
Пришлось вчера на живом все править и чинить, хорошо хоть я базу забэкапил, смог восстановить старые хэши, когда код пегасика их пофырил.

**Comment by Ori-Lama** [comment]
Не получалось, но сейчас вроде получается. Могу попробовать перезапустить браузер и выйти из флудилки.

**Comment by Ori-Lama** [comment]
Не, не воспроизводится. На http заходит с первого щелчка.
