### ISSUE TITLE
Проблемы отображения комментов со спойлерами на странице уведомлений

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#282]
На странице уведомлений в комментах со спойлерами двойной вложенности внешний спойлер открыт, а внутренние закрыты. 
А ссылка на картинку "полосочки" заменена на `https://bunker.lunavod.ru/notifications/#`
![](https://i.imgur.com/Te3IShl.png)

**Comment by MineOzelot** [comment]
Как я понимаю, на странице уведомлений не отображается содержимое комментариев больше, поэтому это неактуально.
