### ISSUE TITLE
Ряд проблем при загрузке картинок

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#289]
Что плохо:
- [x] после попытки загрузить одну или несколько картинок общим объемом больше 8 мб, на форме загрузки картинки больше не нажимается кнопка "Загрузить" и нельзя попытаться загрузить другую картинку пока не обновишь страницу.
- [x] не выводится никаких предупреждающих сообщений о лимите на загрузку, приходится наугад пытаться попасть в разрешенный объем. И при каждой попытке надо обновлять страницу, да.
- [x] во время загрузки на экране не происходит ничего. И ты не знаешь, это произошел сбой или оно просто долго загружается. Нужен какой-то способ отображения прогресса.
- [x] лимит на одну картинку равен лимиту на все картинки. То есть, если ты грузишь пять картинок, то не на каждую будет лимит в 8 мегабайт, а на все пять. Думаю, это не очень практично.
- [x] похоже, если грузить больше 20 картинок, то загрузятся только первые 20. Не в первый раз с таким сталкиваюсь.

(я должен был написать это в раздельные ишшуи или так сойдет?)

**Comment by MineOzelot** [comment]
Отлично, спасибо.
Я, когда-то, лично увеличивал размер ограничения на загрузку, но теперь что-то не так. Возможно, эта проблема пришла с вводом отдельного статик-сервера. Наши статик-серверы очень проблемные, нужно думать что-нибудь об этом..

**Comment by Ori-Lama** [comment]
Добавил еще одну проблему в список.

**Comment by MineOzelot** [comment]
Закрыто в 3a5032862550844ce5426ac1cbce3413e103148e
