### ISSUE TITLE
Гифка, размером в 4,30 КБ не загружается через форму загрузки картинок

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#29]
![вот эта](http://i.imgur.com/D4pnAgr.gif)

**Comment by lunavod** [comment]
Что в network?

**Comment by Ori-Lama** [comment]
![](http://s01.geekpic.net/di-MVGL8Y.png)

**Comment by lunavod** [comment]
Вот тот запрос в network к /, что там в ответе?

**Comment by Ori-Lama** [comment]
![](http://s01.geekpic.net/di-DMEP02.png)
это?

**Comment by lunavod** [comment]
Ага... Блин, странно...
