### ISSUE TITLE
А чего это вы PBKDF2 не используете?

### ISSUE THREAD

**Issue by andreymal** [lunavod/ponydays#291]
Среднестатистическая нвидия позволяет считать сто миллионов этих ваших SHA512 в секунду, а статическая соль ещё и вдобавок даёт возможность построить радужные таблицы. Стырили бы нормальное хэширование пароля из Табуна, что ли

**Comment by MineOzelot** [comment]
Благодарю. Мы уже знаем над кем издеваться за это.
