### ISSUE TITLE
Отвязать аватарки от static-серверов

### ISSUE THREAD

**Issue by MineOzelot** [lunavod/ponydays#292]
Во время отправки комментариев, аватар пользователя отправляется на сторонний сервер, точно так же, как остальные картинки:
https://github.com/lunavod/ponydays/blob/d62519e6b891a70e26407db4027357cf450962ad/classes/actions/ActionBlog.class.php#L1353
Это может вызывать значительные задержки при создании комментария, в зависимости от текущей доступности static-сервера. Так аватары в некоторых комментариях могут вовсе отваливаться, если превышен предел ожидания.
Предлагаю реализовать возможность выбора сервера для загрузки, или, как минимум, определять случай, когда загружать аватарку действительно нужно.

**Comment by lunavod** [comment]
У нас нет по сути отдельного статик сервера же. Статика хранится просто в отдельной папочке на том же хосте... Ну и часть старой - на моем хосте, но туда ничего нового не грузится, он по сути просто фоллбек в nginx - если на локальном не резолвится файл, оно пытается еще от меня его получить.

**Comment by MineOzelot** [comment]
Понятно. Но в чем тогда официальная версия причины падений аватарок в комментах?

**Comment by lunavod** [comment]
Фрум говорил что мой сервер таймаутами кидается... Но это странно, потому что интернет стабильный, на сервере кроме статики вообще ничего нет, по сути только nginx крутится на весь сервер. Надо посмотреть...
