### ISSUE TITLE
Админка

### ISSUE THREAD

**Issue by lunavod** [lunavod/ponydays#3]
Написать свою админку. С графиками и функциями для модераторов.

**Comment by JSkrat** [comment]
о, так из названия-то не видать, что логирование действий админов тоже тут

**Comment by lunavod** [comment]
Так это ж полностью новая админка, без использования частей старых. В админке естественно должно быть логгирование действий, не?

**Comment by JSkrat** [comment]
нет, это неочевидно, что оно там должно быть)

**Comment by JSkrat** [comment]
bump

**Comment by lunavod** [comment]
Хм, а я ведь ее по идее сделал. Можно закрывать.
