### ISSUE TITLE
Низкая производительность прокрутки в Firefox

### ISSUE THREAD

**Issue by sleeply4cat** [lunavod/ponydays#319]
В dark.css и light.css у элемента body выставлен background-blend-mode:screen, это вызывает перерисовку страницы на каждом кадре скролла и драматически роняет фпс.
Убирити >_<

**Comment by MineOzelot** [comment]
Мне понравился факт включения решения этой проблемы в #320. Но я не замечаю значительного изменения производительности. Или не понимаю, как это воспроизвести. К тому же, решение просто поменять на background-blend-mode:normal немного ломает дизайн сайта...

**Comment by sleeply4cat** [comment]
У FF всё плохо с 4к.
https://www.youtube.com/watch?v=PtoG0eXcRfU
На второй части видео всё не настолько печально, как выглядит, просто после устранения затыка перестаёт хватать ресурсов для программы захвата.
Примеры выхлопа профайлера приложил. Первый - со включенным свойством, второй - без.

[profile.zip](https://github.com/Ponydays-Group/ponydays/files/6446186/profile.zip)

**Comment by MineOzelot** [comment]
Закрыто в 99075c9b2cdb455050280ffe686185a0a738d996.
