### ISSUE TITLE
Время отображается не в моем часовом поясе

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#32]
В настройках аккаунта стоит шестой, показывает по третьему.

**Comment by lunavod** [comment]
В постах тоже, или только в комментах?

**Comment by Ori-Lama** [comment]
Не, в постах время правильное, только в комментах. В личках тоже - в постах личек нормально, в комментах личек неправильное.

**Comment by lunavod** [comment]
Ага, отлично. Если бы было иначе, я бы испугался. А это-то вполне себе логично. Просто баг. Сервер возвращает дату по своему часовому поясу, нужно просто перевести ее в универсальный формат и в комментах переделывать в нормальный вид через JS, тогда время норамльное будет.

**Comment by Ori-Lama** [comment]
Баг вернулся, снова в комментах время неправильное.

**Comment by Ori-Lama** [comment]
М, заметил сейчас только. Время неправильное только у комментов, которые я оставляю. А которые были загружены вместе с флудилкой - у тех правильное.
![](http://s01.geekpic.net/di-HMUK8W.png)
![](http://s01.geekpic.net/di-7SURZ8.png)

**Comment by Ori-Lama** [comment]
Кажется баг со временем опять вернулся. А, или он и не был пофикшен?
