### ISSUE TITLE
Картинка в профиле не масштабируется

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#33]
![картинка в профиле](http://s01.geekpic.net/di-AE7RIX.png)

**Comment by Ori-Lama** [comment]
Баг вернулся, но по-другому:
![](http://s01.geekpic.net/di-QNW1YA.png)

**Comment by lunavod** [comment]
Он не вернулся. Это у тебя просто в описании прописана высота картинки через height, а я ограничил ширину до ширины блока.
