### ISSUE TITLE
Менюшка создания некрасивая

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#35]
![](http://s01.geekpic.net/di-US2TSW.png)
Нет никаких красивых кнопок как раньше.

**Comment by lunavod** [comment]
Кнопки отвалились просто. :D

**Comment by Ori-Lama** [comment]
Остальные, однако, на месте.

**Comment by lunavod** [comment]
Да, потому что остальные - иконочный шрифт, я их сам менял, а эти - просто картинки. Их просто нет, они не собираются.
