### ISSUE TITLE
Заголовок блога - тихий ужас

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#36]
Первое - читать длинное описание в таком маленьком окошке со скроллом **неудобно**.
Второе - не показываются все читатели, администраторы и модеры блога как раньше.
Текст на сером спойлере белого цвета.
![](http://s01.geekpic.net/di-GB26GH.png)
Ну и кнопка справа, по которой описание выезжает, раньше хоть была нарисована, а сейчас там белый прямоугольник.

**Comment by lunavod** [comment]
Это я знаю, сейчас именно над этим и работаю.

**Comment by Ori-Lama** [comment]
М, да, нормальное решение. Возможно текстовый бокс стоит немного увеличить, и размер шрифта в нем до размера шрифта в посте. Но это мелочи, ты на правильном пути )
