### ISSUE TITLE
Галочки все еще не галочки, по всему сайту..

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#39]
![](http://s01.geekpic.net/di-WH3U96.png)

**Comment by lunavod** [comment]
Только там, или где-то еще?

**Comment by Ori-Lama** [comment]
Галочки в /settings/tuning/
Ага, в активности вижу исправленные.
В /page/about/ спойлер не открывается (эт не по теме).
В /talk/ в поиске писем галочка "Искать только в избранном".
В /talk/add/ тоже текстовое поле не ресайзится (не по теме).
Ну вроде все. Раньше было по всей личке, но ты уже пофиксил.
