### ISSUE TITLE
Добавление коммента в избранное никак не отображается

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#44]
Что добавил, что убрал из избранного - сердечко выглядит одинаково.

**Comment by Ori-Lama** [comment]
Да, теперь сердечко становится из серого черным. Но только контур, различие в цвете которого слабо заметно. А цифра с количеством добавлений в избранное появляется только после F5 страницы. Мне-то показалось тогда, что она сразу появляется и я подумал "О да, проблема решена. Пусть сердечко и не закрашивается черным, но хоть цифра жирная есть". А оказывается проблема не решена. После щелчка непосредственно сердечко лишь слегка темнеет и никакой жирной цифры нет.

**Comment by lunavod** [comment]
Ай, блин, цифра сломалась после апдейта комментов. 6_9

**Comment by Ori-Lama** [comment]
Все еще не починено.

**Comment by Ori-Lama** [comment]
Все еще не починено.

**Comment by Ori-Lama** [comment]
Все еще не починено.
