### ISSUE TITLE
нет сообщения о проблеме при логине, ничего не происходит

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#46]

**Comment by lunavod** [comment]
Ну, если ошибка одна из заданных - сообщение есть. Сообщения не будет только если или нет ответа от сервера, или JSON из ответа не распарсился и JS завершился с ошибкой.

**Comment by JSkrat** [comment]
там же вроде бы отдаётся текст ошибки. Я видел мешанину урлэнкоднутого юникода в ответе, но ничего не вылезло

**Comment by lunavod** [comment]
Когда именно ты ее видел? Вчера, когда чинили логин?

**Comment by JSkrat** [comment]
да, но я вообще это окошко вижу редко

**Comment by lunavod** [comment]
Это могло быть только вчера, ибо вчера я через echo пытался отлаживать пароли. Так что оно просто не могло распарсить ответ. Если ошибку возвращает, и json валиден, оно выведет ошибку.

**Comment by JSkrat** [comment]
вот неджсон ответа (кроме 413) ни разу не видел
