### ISSUE TITLE
нет сообщения о проблеме при загрузке картинки

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#47]

**Comment by lunavod** [comment]
Тут проблема не в отсутствии сообщения об ошибке. Просто в некоторых случаях загрузка завершается успешно, но возвращается почему-то пустая строка вместо URL картинки. Это на бэке надо разбираться, какого фига.

**Comment by JSkrat** [comment]
я по дебаггеру смотрел, иногда ошибка, но ничего не вылазит

**Comment by lunavod** [comment]
Какая ошибка?

**Comment by JSkrat** [comment]
о, вот к примеру щас вообще 413 вылезло
на большую по байтам картинку, да
