### ISSUE TITLE
отодвинуть кнопку "следующее непрочитанное" подальше от стрелочек-обновляшек

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#52]

**Comment by lunavod** [comment]
Так. А, все же... Зачем? Ибо я в этом смысла вот совсем не вижу. О_о

**Comment by JSkrat** [comment]
чтобы не мазать конечно же! По ней клацаешь быстро, особенно когда проматываешь. Чуть мыша сьехала, и получай обновление комментов и выброс адреналина)

**Comment by lunavod** [comment]
Тогда, если вынести очистку новых комментариев в новую кнопку то это не нужно?

**Comment by JSkrat** [comment]
тогда промах не так критичен будет
