### ISSUE TITLE
Клавиатурная навигация

### ISSUE THREAD

**Issue by Silvman** [lunavod/ponydays#57]
В дополнение к шорткатам:
Сделать возможность полностью клавиатурной навигации. 
Для начала: чтобы можно было открыть поле ответа без щелчка по «ответить» и **рефреш по шорткату**
А потом можно разработать навигацию по коментам с помощью клавы: вроде ctrl+pageup для переключения веток, ctrl+end для перехода в конец, ctrl+up/ctrl+down для перехода по коментам…

**Comment by lunavod** [comment]
Думаю, лучше ctrl на alt заменить - ибо на ctrl всякие браузерные фишки забиндены. Например, по ctrl+pg[up,down] у меня переход по вкладкам.

**Comment by lunavod** [comment]
И, таки, я не очень представляю, как должно работать переключение по веткам. Что считается следующей веткой? Следующий корневой коммент? Или следующий коммент с уровнем, меньшим или равным уровню текущего?

**Comment by lunavod** [comment]
Так, вроде сделал.
ctrl+space - следующий новый
ctrl+up - к комменту сверху
ctrl+down - к комменту снизу
ctrl+home - к первому комменту
ctrl+end - к последнему
alt+pgUp - к ветке выше (т.е. к первому найденному выше корневому)
alt+pgUp - к ветке ниже (т.е. к первому найденному ниже корневому)
alt+r - открыть форму ответа к выделенному комменту
alt+u - апдейт комментов
alt+shift+u - мягкий апдейт комментов (те, что выделенные новыми сейчас, не убираются)
alt+d - деспойл

**Comment by Silvman** [comment]
Надо еще сделать комбинации для закрытия окна ввода и редактирования.
