### ISSUE TITLE
Сделать деспойл (despoil)

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#59]
Я написал по-русски и английски, чтобы в ишшуях можно было находить это слово поиском ) А то сейчас поискал и не нашел - значит ишшуя не открыта.

**Comment by lunavod** [comment]
Да, нет таких.

**Comment by Ori-Lama** [comment]
Теперь я буду стараться искать поиском до того как писать )

**Comment by Ori-Lama** [comment]
Вот, кстати, [пример поста](http://alpha.lunavod.ru/blog/translate-comics/2657), где нужен сразу деспойл и вайдмод.

Хотяяя!.. Эта новая фича с увеличением картинок позволяет смотреть их еще лучше чем вайдмод. Ну, они получаются больше, чем были бы при вайдмоде. Однако при этом на каждую надо кликать.

**Comment by lunavod** [comment]
Там жеж вайдмод только в 12 нужен, остальные и так помещаются в полном размере...

**Comment by Ori-Lama** [comment]
Ну да, просто я сразу увидел эту картинку и пошел писать в ишшую )
