### ISSUE TITLE
ускорить прокрутку к следующему комментарию раза в три-четыре

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#60]

**Comment by JSkrat** [comment]
или полезной была бы кнопка "пометить комментарии ниже этого по ветке прочитанными"

**Comment by Ori-Lama** [comment]
О да, точно, сам хотел предложить, да постеснялся )

**Comment by lunavod** [comment]
Что есть ветка? До комментария, уровень которого меньше или равен текущему? Или до следующего корневого?

**Comment by JSkrat** [comment]
первое (но кажется, будет лучше, если он не будет отмечать больше 10 за раз) и в конце останавливаться на последнем комментарии ветки, а не на следующем непрочитанным за ним

**Comment by lunavod** [comment]
Какой смысл не отмечать больше 10 за раз? О_о

**Comment by JSkrat** [comment]
а вдруг посреди беседы с ботом кто-то вклинится? Вообще не 10, а сколько на экран влазит, но это необязательно, можно просто 8-12

**Comment by JSkrat** [comment]
м, ну или можно вместо этого "отметить все комментарии на экране прочитанными и перейти к следующему" >_>

**Comment by lunavod** [comment]
~~А вообще, может ты таки запустишь у себя и будешь мне помогать, а? D:~~
Я не очень понимаю, при чем тут беседа с ботом. И если смысл кнопки, которая делает прочитанной ветку, я вполне понимаю, то смысл того во что ты это превращаешь - вот совсем не представляю.

**Comment by JSkrat** [comment]
беседа с ботом необязательно будет беседой с ботом до конца ветки же. Т.е. просто хотелось бы такие ветки проматывать быстрее, но не абсолютно быстрее, что аж не видно ничего)

**Comment by lunavod** [comment]
Все равно не вижу смысла. Что мешает сначала быстро проскроллить в своем темпе, а потом нажать на кнопку? Или сначала нажать на кнопку, потом проскроллить беседу вверх, и нажать на переход к следующему новому?

**Comment by JSkrat** [comment]
автообновляшка мешает. Пока проскролливаю появляется новый, я жму "пропустить ветку", а новый появился выше, и проскролливается его ветка. А скроллить туда-сюда ваще костыль. Ну смотри. Есть же стрелки вверх и вниз, а есть pgup/pgdn. Вот "следующий комментарий" это стрелка вниз. А нужен ещё pgdn (я ж уже создавал про то, что нужно и стрелка вверх?)

**Comment by lunavod** [comment]
При автоапдейте нужно новые в конец добавлять...

Да, создавал.

**Comment by JSkrat** [comment]
если ты про очередь на просмотр, то да, в конец, а не скроллить постоянно к следующему, который самый верхний

**Comment by lunavod** [comment]
Сделай на это задачу, плиз

**Comment by JSkrat** [comment]
на очередь просмотра?

**Comment by lunavod** [comment]
Ага
