### ISSUE TITLE
Обновление прямого эфира вместе с комментариями

### ISSUE THREAD

**Issue by lunavod** [lunavod/ponydays#62]

**Comment by Ori-Lama** [comment]
Да, обновление прямого эфира вместе с комментариями сделано. Но получается так, что каждые пару секунд этот прямой эфир мигает, показывает анимированные три полоски загрузки и появляется вновь. Это немного раздражает, потому что он делает это постоянно.
![](http://i.imgur.com/15dbmjs.gif)
Можно ли сделать так, чтобы он обновлялся не мерцая, не исчезая, не показывая анимацию? Просто бам - и строчки меняются. А если не меняются, то не происходит никакого мигания, строчки просто не меняются.

**Comment by lunavod** [comment]
Ты обновляешь комменты каждые пару секунд?

**Comment by Ori-Lama** [comment]
У меня автообновление включено. На гифке видно - каждые секунд 9 оно мерцает.
