### ISSUE TITLE
очередь просмотра новых комментариев: не от самого верхнего, а по мере появления

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#64]

**Comment by Ori-Lama** [comment]
И меня будет швырять туда-сюда по всей флудилке? С этим же, помнится, уже боролись и на табуне, и на старом бункере, и на новом бункере..

**Comment by JSkrat** [comment]
ни разу такого не видел, разве было?
если как сейчас, то при активном флуде ты сидишь в верхних ветках и нифига не видишь, что внизу творится. Мя несколько раз так добирался к низу через час или больше, а меня там уже призывали несколько раз

**Comment by lunavod** [comment]
@Ori-Lama не, тут не про это. Это к тому, чтобы комментарии, которые были подгружены через автоапдейт добавлялись в конец списка новых.

**Comment by lunavod** [comment]
Хотя это тоже спорное решение...

**Comment by Ori-Lama** [comment]
Ну, может быть я не понял что ты хотел сказать? Я так понял, что ты хочешь, чтобы комменты проматывались *по дате* создания, а не просто сверху вниз по порядку. Такое было неоднократно, на недоработанных версиях табуна и бункера, и мы ныли, и программисты фиксили.

Ага, при активном флуде тебе хочется видеть разные ветки в реальном времени. Окей, сделайте тогда это отключаемой опцией, чтобы я мог бы это выключить. Потому что при не активном флуде, а при чтении уже имеющейся непрочитанной флудилки очень неудобно, когда тебя туда-сюда фигачит от коммента к комменту. Обычно же читаешь ветку сверху вниз, а не разные ветки по мере их создания.

**Comment by lunavod** [comment]
Не, Ори. Ты все еще не понимаешь, о чем я говорю. Вот смотри:
Ты включаешь автоапдейт. Начинаешь пролистывать кнопкой много новых комментов. Потом автоапдейт срабатывает, и тебе подгружает комменты, которые еще и выше. И при следующем клике тебя переносит не, например, к следующему комменту в ветке, а куда-то сильно выше, ибо туда добавили комментарий, и его подгрузило автоматически. И это фигово. А я предлагаю считать комменты все так же сверху вниз, но при этом если комментарии подгружены через автоапдейт, то добавлять их после тех, которые были подгружены изначально. Хотя нет, лучше сделать не совсем так, а чтобы те комменты, которые идут выше по дереву, чем тот, который сейчас выделен через goToNextComment, добавлялись вниз, а те, которые ниже - в обычное место. Т.е. читать ты будешь, пока не дойдешь до самого низа, а потом тебя перебросит к новым комментариям сверху. А потом все повторится. Т.е. суть в том, что ты идешь сверху вниз по странице, и тебя перебрасывает к новым сверху только после того, как ты дойдешь до низа.

**Comment by Ori-Lama** [comment]
Мммм, это хорошо, это понятно. Обычный принцип "сверху вниз" сохраняется, а новые комменты, полученные при автообновлении будут прощелкиваться после того как я прощелкаю текущую ветку, например. Это хорошо, да.

**Comment by JSkrat** [comment]
та ну. Просто очередь применять лишь к подгруженным автоапдейтом комментариям
