### ISSUE TITLE
клик на Ориспойлер с картинкой открывает и спойлер и картинку, это как-то неправильно

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#65]

**Comment by lunavod** [comment]
Ну... Можно разве что сделать так, чтобы открытие на полный размер активировалось только с картинками больше определенного размера...

**Comment by Ori-Lama** [comment]
А можно сделать как на предыдущем бункере - чтобы все действия с объектами на спойлере делались средней кнопкой мыши, а левой он бы открывался. Сделали же такое с ссылками там?

**Comment by lunavod** [comment]
Эм... Шта? Когда такое было на бункере? И при чем тут ссылки? А еще средняя кнопка мыши браузерами перехватывается на всем кроме ссылок, вроде.

**Comment by Ori-Lama** [comment]
Ну дык, делали же. Проблема была в том, что на кнопке спойлера были ссылки - на профиль или просто так куда-то, и человек щелкал и переходил по ссылке, вместо того чтобы открыть спойлер. Поэтому это отключили, и теперь можно перейти по ссылке, нажав среднюю кнопку, а нажав левую просто открыть спойлер.

**Comment by lunavod** [comment]
Нееееет, не делали... О_О

**Comment by Ori-Lama** [comment]
Значит оно само получилось так? :) Посмотри [на бункере](https://bunker.lunavod.ru/blog/flud/2651#comment948198).
