### ISSUE TITLE
обработчик картинок игнорирует метаинфу о повороте изображения

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#68]
оригинал
http://jsk.pp.ua/b/IMG_20170315_012130.jpg

что вышло
http://alpha.lunavod.ru/img/1a48b1a4.jpg

**Comment by JSkrat** [comment]
гм. Если так открывать, то норм. А если в посте, то http://alpha.lunavod.ru/blog/craft/2658

**Comment by JSkrat** [comment]
ага, это вообще известный баг, и тут предлагают его решить js-сниппетом
http://stackoverflow.com/questions/12026441/is-there-a-way-to-tell-browsers-to-honor-the-jpeg-exif-orientation

**Comment by JSkrat** [comment]
окей, как открыть обратно? <_>

**Comment by Frumscepend** [comment]
![image](https://user-images.githubusercontent.com/5337923/41817818-7c907662-77cc-11e8-962f-51948f5eeee3.png)

**Comment by JSkrat** [comment]
https://i.imgur.com/nlLYWb5.png
пегасик недостаточно прав

**Comment by Frumscepend** [comment]
@JSkrat А, ну значит тебе не открыть...

**Comment by Frumscepend** [comment]
Лол. Она типа открыта, но так как назначена на @JSkrat, то следовательно `wontfix` :D

**Comment by JSkrat** [comment]
а ты шо, пофиксить хочешь?

**Comment by Frumscepend** [comment]
Не, я кекаю с ситуации)

**Comment by JSkrat** [comment]
кекай, а закрывать нинада, а то опять вместо фиксов буду заниматься непойми чем навроде отлавливания Лу и приставания на предмет открыть обратно

**Comment by Frumscepend** [comment]
Ну так пофикси, разорви круг!

**Comment by JSkrat** [comment]
пофиксию, который месяц вкладки со стековерфлоу об этом висят

**Comment by Frumscepend** [comment]
![fec04cc7a5dd219d4642e174fc83c5a7](https://user-images.githubusercontent.com/5337923/44621264-34a83100-a8cd-11e8-84da-b285a72eb43b.jpg)

**Comment by MineOzelot** [comment]
Ну, теперь она ещё больше wontfix. Закрываю.
