### ISSUE TITLE
Прямой эфир не показывает блог, в котором был оставлен коммент

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#70]
![](http://s01.geekpic.net/di-0K87TP.png)
И то, и другое - флудилка. Только верхняя в Розе, а нижняя обычная.

**Comment by lunavod** [comment]
http://i.imgur.com/sI4o0Ih.png
 или
http://i.imgur.com/cFiUOmb.png
?

**Comment by Ori-Lama** [comment]
sI4o0Ih лучше, потому что оно не будет прыгать со строчки на строчку. Ну и скобочки можно убрать.
