### ISSUE TITLE
У модератора нет кнопок редактирования и удаления комментариев, просмотра истории редактирования

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#71]
Сосбна, раз с аналогичным кнопками в заголовке поста разобрались, почему бы и для комментов не сделать?

**Comment by lunavod** [comment]
А у них их нет?

**Comment by Ori-Lama** [comment]
А я на альфе модератор чего? Внешки или конкретно флудилки? У меня есть кнопки редактирования поста, чтобы перекаты делать, а кнопки редактирования комментов нет.
![](http://s01.geekpic.net/di-QQVRKV.png)
Зато есть кнопка редактирования своих комментов )
![](http://s01.geekpic.net/di-FKYE7K.png)
