### ISSUE TITLE
Что-то у меня на альфе fps заметно проседает

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#73]
Особенно во время обновления комментариев. На предыдущем бункере такого не было.
[На альфе](https://youtu.be/iSP59ihJRtE).
[На бункере](https://youtu.be/RwCa3ebN2D8).

В общем, невооруженным взглядом заметно, что альфа куда более тормознутая. При включении вайд-мода на бункере тоже немного уменьшается производительность, но почти незаметно, на видео не видно даже будет.

**Comment by lunavod** [comment]
Эх... Видимо, действительно придется отказаться от реакта и заюзать обычный рендеринг через строки.

**Comment by Ori-Lama** [comment]
После перезапуска браузера fps снова хороший, все летает еще лучше чем на бункере. А не связано ли проседание с тем, что страница долго автообновлялась и добавлялись комменты? А когда я перезагрузил ее, то она типа свежая и все быстро работает.

**Comment by lunavod** [comment]
Можешь проверить сейчас? Конечно, по идее тут нужно подождать некоторое время, но если это действительно зависит от обновления комментов, то будет достаточно много-много раз прожать кнопку апдейта.

**Comment by Ori-Lama** [comment]
Ага, понажимаю, посмотрю.

**Comment by Ori-Lama** [comment]
Понажимал раз 20, заметно тормозить не начало. Возможно нужно куда больше чем 20. До этого у меня флудилка была открыта больше пары часов, наверное.

**Comment by lunavod** [comment]
Хм. А у тебя при конкретно апдейте флудилки, страница не перестает скроллиться? В смысле, при апдейте комментов там.

**Comment by Ori-Lama** [comment]
Вот если взять и потихоньку скроллить и в этот момент произойдет апдейт комментариев, то скролл ненадолго приостановится.

**Comment by Ori-Lama** [comment]
И если сидеть и набирать текст комментария, и при этом происходит обновление комментов, то буквы в поле ввода появятся с небольшой задержкой. Вот такого на бункере я точно не замечал раньше. Тут задержка заметна.

**Comment by Ori-Lama** [comment]
Вот что еще добавлю по этому поводу, сегодня заметил с утра. После щелчков на спойлеры с большими картинками под ними, подлагивание это усиливается. Например сильно было заметно после щелчка на [эту картинку](http://alpha.lunavod.ru/blog/flud/2659#comment952380).

Тем не менее, в посте с комиксами от Ведонта такого подвисания нет. Но там и комментов нет.

Но опять же, обновление страницы избавляет от лагов.
И после обновления я щелкаю на ту же картинку и лаги не появляются.

**Comment by lunavod** [comment]
Так, теперь по идее не должно лагать.

**Comment by lunavod** [comment]
@Ori-Lama

**Comment by Ori-Lama** [comment]
А я и без этого обращения получаю емейлы.

**Comment by lunavod** [comment]
Это я на всякий случай. Я просто так пытаюсь у тебя спросить, лагает ли у тебя все еще, или я таки пофиксил и могу закрывать задачу. 6_9

**Comment by Ori-Lama** [comment]
А чтобы это протестить нужно время )
Пока вроде с тех пор как это обновление накатилось, не лагает.

**Comment by lunavod** [comment]
Ладно, тогда пока закрою. Если потом будут проблемы, открою.
