### ISSUE TITLE
После принятия дружбы на альфе ссылка переносит на бункер

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#84]

**Comment by Ori-Lama** [comment]
Кстати, а где в профиле друзья вообще? Чет этот новый профиль потерял почти все что было раньше.

**Comment by lunavod** [comment]
![fdhjdfhdcghfhgdfhg](https://cloud.githubusercontent.com/assets/14801311/24239212/1d0684d8-0fbe-11e7-9438-d10e315b1b74.png)

**Comment by Ori-Lama** [comment]
А.
Ну, все равно часть юзабилити потеряно.

**Comment by lunavod** [comment]
Ну, блин, а кто-то вообще смотрел в тот список?

**Comment by Ori-Lama** [comment]
Я смотрел. Я только там друзей пользователя и находил, это было быстро. Но он часто был неполный, в отличие от табуна, поэтому приходилось нажимать ссылку на полный список. На табуне лучше, сразу полный список, все иконки.
