### ISSUE TITLE
Переделать загрузку картинок

### ISSUE THREAD

**Issue by lunavod** [lunavod/ponydays#9]

**Comment by JSkrat** [comment]
не отображаемая ошибка 413 при аплоаде картинок с компа — это сюда или в новый issue?

**Comment by lunavod** [comment]
Не сюда. Эта задача вообще для другого, это глобальная фиговина. Она включает себя систему тегирования картинок, комменты к картинкам, фильтры, и соответственно измененную загрузку.

**Comment by JSkrat** [comment]
D: да тебя фиг поймёшь тогда. Чтобы не ругался больше на создание "дублей"! *пошёл создавать*
