### ISSUE TITLE
Не получается закрыть комменты в посте

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#90]
Галочка совсем не нажимается. [Этот пост](http://alpha.lunavod.ru/topic/edit/2689/)

**Comment by lunavod** [comment]
Хм, закрыл? В чем была проблема?

**Comment by Ori-Lama** [comment]
Ну, нажимал на галочку - ничего не происходило.

**Comment by Ori-Lama** [comment]
Ааа. Почему я эту ишшую закрыл. Потому что я отправлял форму с ишшуей и закрыл вкладку. Думал что не отправилось и создал новую. А оказалось что отправилась, так что новую закрыл.
