### ISSUE TITLE
Новый деспойл закрывает открытые спойлеры и открывает закрытые

### ISSUE THREAD

**Issue by Ori-Lama** [lunavod/ponydays#94]
А старый приводил все сначала в одно состояние - открытое или закрытое, потом в другое. То есть нельзя было открыть первый и третий, нажать деспойл и они оказались бы закрыты.

**Comment by lunavod** [comment]
Это плохо, да? Окей, буду чинить...

**Comment by Ori-Lama** [comment]
Ну, когда я хочу все закрыть, я хочу все закрыть ) А не закрыть половину.

**Comment by Ori-Lama** [comment]
Теперь спойлеры только открываются и не закрываются обратно. А еще происходит перемотка наверх страницы.

**Comment by lunavod** [comment]
http://imgur.com/a/WW3Eu

**Comment by Ori-Lama** [comment]
Сейчас проверил - все работает правильно. А тогда почему-то неправильно было. Я нажимал на деспойл и переносился в верх страницы. И они не все закрывались. Хм, может это конкретно в той флудилке какой-то баг в самих спойлерах.. Перепроверил - нет, сейчас все нормально.

**Comment by Ori-Lama** [comment]
О, нашел! В 909-й флудилке все еще неправильно.

**Comment by lunavod** [comment]
Ааа, ну ясно. Это то, что бывает, если делать spoiler-body без spoiler-title.

**Comment by Ori-Lama** [comment]
Уж не я ли сделал такую гадость? Кажется я.

**Comment by Ori-Lama** [comment]
Аааа, не, Ози же.
