### ISSUE TITLE
Подсветить комменты непрочитанными после этого (готовое решение для бункера на JS)

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#95]
https://alpha.lunavod.ru/blog/flud/2254#comment762557

**Comment by lunavod** [comment]
А оно таки нужно? Действительно редко используется, и я не знаю, куда это впихнуть. =/

**Comment by JSkrat** [comment]
прост в избранном у себя нашёл... кейз - когда упала страничка с непрочитаными, или свет погас, или... но нужно редко, да. Но Ори тоже юзал, помню

**Comment by lunavod** [comment]
Ну так да, это все в той ветке написано. Но я даже не представляю, в какую кнопку это запихнуть  можно. =/

**Comment by JSkrat** [comment]
по идее это относится к конкретному каменту, знач на каментах следует такое ставить, но где-нить чтобы не мешалось... или тупо сделать функцию с коротким именем, чтобы можно было из консоли вызывать, тогда точно мешаться не будет

**Comment by JSkrat** [comment]
но тогда в хелпе про функцию няписать, да

**Comment by lunavod** [comment]
Нам нужен терминал на js, чтобы вызывать из него функции, записанные в JS!

**Comment by JSkrat** [comment]
так есть же консоль

**Comment by lunavod** [comment]
Ну так а нам нужна еще одна, только в интерфейсе. XD

**Comment by JSkrat** [comment]
но зачем дублировать то, что уже няписано нативно?

**Comment by lunavod** [comment]
Чтобы было красиво. :D
Шучу я, ну...

**Comment by JSkrat** [comment]
прям в хелпе поле ввода и кнопка с именем функции, хы
