### ISSUE TITLE
нужно сделать отдельный домен для картинок

### ISSUE THREAD

**Issue by JSkrat** [lunavod/ponydays#99]
а то бардак, одни в каментах бункер пишут, другие альфу, а потом снесёшь домен альфа, сделав её основной, и картинки полетят

**Comment by lunavod** [comment]
Не полетят. Это решается переносом картинок с альфы на static, и заменой ссылок в базе.

**Comment by lunavod** [comment]
И таки делать загрузку на альфу не стоит - это ж не будет работать на локалках.

**Comment by JSkrat** [comment]
в смысле?

**Comment by lunavod** [comment]
В смысле, что фиг это запустишь на локалке - загрузка картинок работать не будет. Хотяяя, это же вагга. С ней в принципе можно попробовать.
